spring:
  r2dbc:
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
logging:
  level:
    org:
      springframework: @spring.logging@
server:
  error:
    include-stacktrace: on-param

