spring:
  r2dbc:
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
#    url: r2dbc:postgresql://localhost:15432/spring_webflux_essentials
#    username: spring_webflux_essentials
#    password: abc12345
logging:
  level:
    org:
      springframework: @spring.logging@
#      springframework: DEBUG
server:
  error:
    include-stacktrace: on-param

