name: CI/CD - Development

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
#    runs-on: ubuntu-latest
    runs-on: self-hosted   

    steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    
    - id: set-up-jdk11 
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - id: cache-sonarcloud-packages
      name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Download Maven
      run: |
        curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
        apt-get update
        apt-get -y install unzip
        unzip -d /usr/share maven.zip
        rm maven.zip
        ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
        echo "M2_HOME=/usr/share/apache-maven-3.6.3" | tee -a /etc/environment
        
    - id: build-and-analyze
      name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        NEXUS3_USERNAME: ${{ secrets.NEXUS3_USERNAME }}
        NEXUS3_PASSWORD: ${{ secrets.NEXUS3_PASSWORD }}
        R2DBC_DATABASE_URL: postgres-svc
        R2DBC_DATABASE_USERNAME: spring_webflux_essentials
        R2DBC_DATABASE_PASSWORD: abc12345
        LOGGING: DEBUG
      run: mvn -s settings.xml -B verify deploy org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=cams7-tests_spring-webflux-essentials --file pom.xml
